In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/TweetsCOV19.tsv',sep = '\t',skiprows = list(range(4467891,8935782)),usecols=range(11),iterator=True, chunksize=4460000)
df = pd.concat(data, ignore_index=True)
data2 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/TweetsCOV19.tsv',sep = '\t',skiprows = list(range(4467891)),usecols=range(11),iterator=True, chunksize=4460000)
df2 = pd.concat(data2, ignore_index=True)
frame = pd.concat([df,df2])

In [ ]:
frame = pd.concat([pd.read_csv('/content/drive/My Drive/Colab Notebooks/TweetsCOV19.tsv',sep = '\t',skiprows = list(range(4467891,8935782)),usecols=range(11),header=None),pd.read_csv('/content/drive/My Drive/Colab Notebooks/TweetsCOV19.tsv',sep = '\t',skiprows = list(range(4467891)),usecols=range(11),header=None)])

frame.columns = ['Tweet Id', 'Username', 'Timestamp', 'Followers', 'Friends', 'Retweets', 'Favorites', 'Entities', 'Sentiment', 'Mentions', 'Hashtags']

In [ ]:
frame['Timestamp'] = frame.Timestamp.apply(lambda x: x.split())

In [ ]:
frame['Day'] = frame.Timestamp.apply(lambda x: x[0])

In [ ]:
frame['Month'] = frame.Timestamp.apply(lambda x: x[1])
frame['Date'] = frame.Timestamp.apply(lambda x: x[2])
frame['Time'] = frame.Timestamp.apply(lambda x: x[3].split(':')[0])
frame['Year'] = frame.Timestamp.apply(lambda x: x[5])

In [ ]:
frame['Pos'] = frame.Sentiment.apply(lambda x: int(x.split()[0]))

In [ ]:
frame['Neg'] = frame.Sentiment.apply(lambda x: int(x.split()[1]))

In [ ]:
frame = frame.drop(columns=['Timestamp','Entities','Username','Sentiment'])

In [ ]:
frame.replace('null;', np.NaN,inplace=True)

In [ ]:
frame.Hashtags.loc[pd.notnull(frame.Hashtags)]

In [1]:
from google.colab import drive
drive.mount('drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at drive


In [ ]:
frame.to_csv('data.csv')
!cp data.csv "drive/My Drive/Colab Notebooks/"

In [2]:
import pandas as pd
import numpy as np
frame = pd.read_csv('/content/drive/My Drive/Colab Notebooks/comp9417/data.csv')
#convert month to number
#convert day of week to number

month_map={'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11 , 'Dec':12}
frame.Month = frame.Month.map(month_map)

day_map={'Mon':1, 'Tue':2, 'Wed':3, 'Thu':4, 'Fri':5, 'Sat':6, 'Sun':7}
frame.Day = frame.Day.map(day_map)

drop_col=['Unnamed: 0', 'Tweet Id','Mentions', 'Hashtags']
frame.drop(drop_col,axis=1,inplace=True)

print(frame.Retweets.unique())
print(len(frame.Retweets.unique()))

Y = frame.pop('Retweets')
X=frame


[    0    13    26 ...  6816  3868 10791]
9441


In [1]:
#VIF
from scipy.linalg.lapack import spotrf, sposv
import numpy as np
import pandas as pd

def variance_inflation_factor(X):
    """
    Calculates the variance inflation factor for each column in a dataframe.
    Input:
        X: Dataframe
    Output:
        Dataframe of variance inflation values for each column.
    """
    isDataframe = type(X) is pd.DataFrame
    if isDataframe:
        columns = X.columns
        X = X.values
    n, p = X.shape

    swap = np.arange(p)
    np.random.shuffle(swap)

    XTX = X.T @ X
    XTX = XTX[swap][:,swap]

    select = np.ones(p, dtype = bool)

    temp = XTX.copy().T
    error = 1
    largest = XTX.diagonal().max() // 2
    add = largest
    maximum = np.finfo(np.float32).max

    while error != 0:
        C, error = spotrf(a = temp)
        if error != 0:
            error -= 1
            select[error] = False
            temp[error, error] += add
            error += 1

            add += np.random.randint(1,30)
            add *= np.random.randint(30,50)
        if add > maximum:
            add = largest

    VIF = np.empty(p, dtype = np.float32)
    means = np.mean(X, axis = 0)[swap]

    for i in range(p):
        curr = select.copy()
        s = swap[i]

        if curr[i] == False:
            VIF[s] = np.inf
            continue
        curr[i] = False

        XX = XTX[curr]
        xtx = XX[:, curr]
        xty = XX[:,i]
        y_x = X[:,s]

        theta_x = sposv(xtx, xty)[1]
        y_hat = X[:,swap[curr]] @ theta_x

        SS_res = y_x-y_hat
        SS_res = np.einsum('i,i', SS_res, SS_res)
        #SS_res = np.sum((y_x - y_hat)**2)

        SS_tot = y_x - means[i]
        SS_tot = np.einsum('i,i', SS_tot, SS_tot)
        #SS_tot = np.sum((y_x - np.mean(y_x))**2)
        if SS_tot == 0:
            R2 = 1
            VIF[s] = np.inf
        else:
            R2 = 1 - (SS_res/SS_tot)
            VIF[s] = 1/(1-R2)
        del XX, xtx, xty, y_x, theta_x, y_hat
    if isDataframe:
        df_vif = pd.DataFrame({"vif": VIF})
        df_vif = df_vif.set_index(columns)
        return df_vif
    return VIF

In [ ]:
import pandas as pd, numpy as np, os, gc, matplotlib.pyplot as plt, seaborn as sb, re, warnings, calendar, sys
from copy import deepcopy
import statsmodels.api as sm
from math import log2
from collections import defaultdict
import seaborn as sns; sns.set()
from sklearn import preprocessing
train_set=pd.read_csv('train.csv')
test_set=pd.read_csv('test.csv')

train_set.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1,inplace=True)
test_set.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1,inplace=True)
Y = train_set.pop('bin')
X= train_set
print(X)
model = sm.OLS(Y, X).fit()
print(model.summary())
# A VIF of 1 indicates two variables are not correlated, a VIF between 1 and 5 indicates moderate correlation, and a VIF above 5 indicates high correlation.
vif= variance_inflation_factor(X)
df_coeffs = pd.DataFrame({"Coefficients": model.params, "p": model.pvalues, "vif": vif["vif"]})
# df_coeffs = df_coeffs.drop("const", axis=0)

df_coeffs.style.bar(subset = ["Coefficients", "p", "vif"], align='mid', color=['#d65f5f', '#5fba7d'])
df_coeffs

                  Tweet Id  Followers  Friends  Favorites  Day  Month  Date  \
0      1216392803632197632      53076      799         61    7      1    12   
1      1224190295513817088       3970      530         81    1      2     3   
2      1233349182888517633      15767    13932         48    5      2    28   
3      1247138584949374983       6838     5736         56    1      4     6   
4      1241735776527884290       1319      290         41    7      3    22   
...                    ...        ...      ...        ...  ...    ...   ...   
43970  1242539912626397184      19567     3307      34087    2      3    24   
43971  1241774965642473479       2575      743      97227    7      3    22   
43972  1241717148390690817        668       82      24475    7      3    22   
43973  1234208058399739906       1942      192      80732    7      3     1   
43974  1221973312898646016       1538      453      54193    2      1    28   

       Time  Year  Pos  Neg  Mentions_count  Hashta

In [2]:
import time
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,recall_score
from sklearn.ensemble import RandomForestClassifier

print(X.shape,Y.shape)
print(Y.unique())
X_RF=X[:10000]
Y_RF=Y[:10000]
print(len(Y_RF.unique()))
Y_RF = LabelEncoder().fit_transform(Y_RF)
X_RF = StandardScaler().fit_transform(X_RF)

# print(len(X[0]))
# X_RF=X_RF[:10000]
# Y_RF=Y_RF[:10000]



def forest_test(X, Y):
    X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, 
                                                        test_size = 0.30, 
                                                        random_state = 42)
    print(X_Train.shape,X_Test.shape,Y_Train.shape, Y_Test.shape)
    start = time.process_time()
    trainedforest = RandomForestClassifier(n_estimators=500,random_state=1).fit(X_Train,Y_Train)
    print('time to fit RF',time.process_time() - start)
    predictionforest = trainedforest.predict(X_Test)
    print('accuracy score',accuracy_score(Y_Test,predictionforest))
    # print('recall score', recall_score(Y_Test,predictionforest,average='micro'))
    # print(confusion_matrix(Y_Test,predictionforest))
    # print(classification_report(Y_Test,predictionforest))

forest_test(X_RF, Y_RF)

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


(8077794, 10) (8077794,)
[    0    13    26 ...  6816  3868 10791]
420
(7000, 10) (3000, 10) (7000,) (3000,)
time to fit RF 25.852219863
accuracy score 0.6233333333333333


In [ ]:
# import joblib
# import pandas as pd
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import GridSearchCV
# import warnings
# warnings.filterwarnings('ignore', category=FutureWarning)
# warnings.filterwarnings('ignore', category=DeprecationWarning)
# from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import StandardScaler

# X_RF=X[:10000]
# Y_RF=Y[:10000]
# print(len(Y_RF.unique()))
# Y_RF = LabelEncoder().fit_transform(Y_RF)
# X_RF = StandardScaler().fit_transform(X_RF)

# def print_results(results):
#     print('BEST PARAMS: {}\n'.format(results.best_params_))

#     means = results.cv_results_['mean_test_score']
#     stds = results.cv_results_['std_test_score']
#     for mean, std, params in zip(means, stds, results.cv_results_['params']):
#         print('{} (+/-{}) for {}'.format(round(mean, 3), round(std * 2, 3), params))

# rf = RandomForestClassifier()
# parameters = {
#     'n_estimators': [250,500],
#     # 'max_depth': [8, 16, 32, None]
# }

# print(X_RF.shape,Y_RF.shape)
# cv = GridSearchCV(rf, parameters, cv=5)
# cv.fit(X_RF, Y_RF)

# print_results(cv)


420
(10000, 10) (10000,)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)


In [11]:
#Linear Regression
from sklearn import metrics
import time
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, 
                                                        test_size = 0.30, 
                                                        random_state = 42)
print(X_Train.shape,X_Test.shape,Y_Train.shape, Y_Test.shape)
start = time.process_time()
model=LinearRegression()
model.fit(X_Train,Y_Train)
print('Time to fit model',time.process_time() - start)
predictions=model.predict(X_Test)
print('Return the coefficient of determination R^2 of the prediction.',model.score(X_Test,Y_Test))
print('Mean squared log error MSLE',metrics.mean_squared_log_error(Y_Test,predictions))
# plt.scatter(Y_Test,predictions)
# plt.xlabel("Actual Retweets")
# plt.ylabel("Predicted Retweets")
# plt.show()

#k-fold cross validation
model=LinearRegression()
cv_4_results = cross_val_score(model, X, Y, cv=5)
cv_4_results


(5654455, 10) (2423339, 10) (5654455,) (2423339,)
Time to fit model 1.6940796250000005
Return the coefficient of determination R^2 of the prediction. 0.829673768373932
Mean squared log error MSLE 3.5612113242821137


array([0.7327294 , 0.72533973, 0.85255705, 0.81285665, 0.76812381])

In [8]:
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn import metrics
import time
from sklearn.model_selection import train_test_split
# print(RandomForestClassifier())
# print(RandomForestRegressor())

X_RF=X[:100000]
Y_RF=Y[:100000]

X_Train, X_Test, Y_Train, Y_Test = train_test_split(X_RF, Y_RF, 
                                                        test_size = 0.30, 
                                                        random_state = 42)
print(X_Train.shape,X_Test.shape,Y_Train.shape, Y_Test.shape)
start = time.process_time()
model=RandomForestRegressor()
model.fit(X_Train,Y_Train)
print('Time to fit model',time.process_time() - start)
predictions=model.predict(X_Test)
print('Return the coefficient of determination R^2 of the prediction.',model.score(X_Test,Y_Test))
print('Mean squared log error MSLE',metrics.mean_squared_log_error(Y_Test,predictions))

(70000, 10) (30000, 10) (70000,) (30000,)
Time to fit model 45.455493115000024
Return the coefficient of determination R^2 of the prediction. 0.4157344650943916
Mean squared log error MSLE 0.2517106097499519
